repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.23
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
      - id: terragrunt-hclfmt
      - id: tflint
        args:
          - "--config=__GIT_ROOT__/.tflint.hcl"
      - id: shellcheck
      - id: gofmt
      - id: golint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-json
